### ISSUE TITLE
v0.1.1 checklist

### ISSUE THREAD

**Issue by eahenle** [SimonEnsemble/PoreMatMod.jl#73]
- [x] wget to d/l files for the example pluto notebooks and/or link to files on github. [1]
 - [x] mention color scheme in every notebook for the ! atoms
 - [x] consider generalizing the viz of ! atoms. put mesh around ! atoms or somehow annotate them in Bio3Dview. post issue to ask if there is a way to annotate? [2]
 - [x] add verbose::Bool=false, print stuff off as times goes on to inform user. I think this is important for quick feedback to explain optional arguments.
 - [x] describe how ori entry zero means that u have control over which are random.
 - [x] replicate output of disorder correction to make sure handles across PB correctly.
 - [x] simplify to have only two isomorphisms.  handle as dictionaries? [3]
 - [x] enforce testing only of unique replacement-to-parent mappings (don't waste time on duplicates)
 - [x] change license to MIT
 - [x] add test on result coords for verified loc/ori replacement
 - [x] examples in examples/
 - [x] `using ZipFile` in notebooks, instead of in helper.jl
 - [x] use `Downloads` pkg
 - [x] verify removal of pre-registration hacks
 - [x] name coord-like vars to indicate fractional vs. Cartesian

**Comment by eahenle** [comment]
notebooks now download `examples.zip` if `data/` is not found

**Comment by eahenle** [comment]
[2] posted issue to ask about annotations.  they are possible in the underlying JS library, will see if that's accessible to us.

**Comment by eahenle** [comment]
[3] Given that two searches must be done and the queries are not the same between the two, I don't think the number of mappings can be reduced.  If we have `q in p` and `q\prime in r` we must have a mapping from `q` to `q\prime` to compose the bijections to get `r\prime` to `p`.

**Comment by SimonEnsemble** [comment]
at very end, change top cell of example notebooks; currently set up for `dev`. also check link to examples folder in the input file description.

**Comment by SimonEnsemble** [comment]
a way to automate converting the example notebooks into `.html` and `mv` them to the `docs` folder in appropriate place or get referred to by docs. github action?
